-- Generated by ~/.config/quickshell/scripts/theme-sync.py (theme: crimson) — read by
-- ui/theme.lua; set `[sync] hyprland = false` in config/shell.conf to go back to its own palette.
return {
    enabled = true,
    active = { "rgba(ffffffee)", "rgba(d0142fee)", "rgba(ff7a8aee)" },
    angle = 45,
    inactive = "rgba(120f0f66)",
    shadow = 0x2ad0142f,
    shadow_idle = 0x08000000,
}
