-- Generated by ~/.config/quickshell/scripts/theme-sync.py (theme: nier) — read by
-- ui/theme.lua; set `[sync] hyprland = false` in config/shell.conf to go back to its own palette.
return {
    enabled = true,
    active = { "rgba(fff6cfee)", "rgba(c8b89aee)", "rgba(b0493fee)" },
    angle = 45,
    inactive = "rgba(221e1766)",
    shadow = 0x2ac8b89a,
    shadow_idle = 0x08000000,
}
